name: hello_world

on:
  push:
    branches: [practica]

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - run: pip install pytest unittest

      - run: pip install -r requirements.txt

      - run: python main_test.py
